name = "web-api"
type = "javascript"

account_id = "dec5faaa291bed5cb16ea79d3b88301f"
workers_dev = true

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "application-0-sbkdl"